project:
  type: website
  output-dir: docs

website:
  title: "Linus Ma"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: blog.qmd
        text: Blog
      - href: roles.qmd
        text: Selected Theatre Roles
      - href: https://linuswashere.github.io/testblog
        text: My Actual Blog

format:
  html:
    theme:
      - cosmo
      - brand
      - lumen
      - solar
    css: styles.css
    toc: true



